name: Build and Publish image to Docker Hub
on:
  push:
    branches:
      - main
      - pull_request
    paths:
      - 'api/Dockerfile'  
      - 'front-end-nextjs/Dockerfile'

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: |
          docker build ./api/ -t indra9392698146/devops-qr-code-backend:latest
          docker build ./front-end-nextjs/ -t indra9392698146/devops-qr-code-frontend:latest
      - name: push image to docker hub
        run: |
          docker login -u indra9392698146 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push indra9392698146/devops-qr-code-backend:latest
          docker push indra9392698146/devops-qr-code-frontend:latest
